# Generated by Django 2.2.3 on 2020-10-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='title',
            field=models.CharField(default=-1.0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.ImageField(blank=True, upload_to='users/%Y/%m/%d/'),
        ),
    ]
